name: auto-clang-format

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

permissions:
  contents: write

jobs:
  clang-format:
    name: Check and Fix Code Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Install Clang-Format
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Run Clang-Format Check
        id: format_check
        run: |
          if find src/ -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror; then
            echo "formatted=true" >> $GITHUB_ENV
          else
            echo "formatted=false" >> $GITHUB_ENV
          fi

      - name: Apply Clang-Format Fixes
        if: env.formatted == 'false'
        run: |
          find src/ -name '*.cpp' -o -name '*.h' | xargs clang-format -i

      - name: Commit and Push Changes
        if: env.formatted == 'false'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-format: Applied clang-format fixes"
          git push origin dev